#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2003 Preston Elder <prez@magick.tm>
# (c) 1998-2003 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the Artistic License v2.0 or better.
# The full text of this license should be contained in a file called
# COPYING distributed with this code.  If this file does not exist,
# it may be viewed here: http://www.magick.tm/m2/license.html
#
# =======================================================================
#
# For official changes (by the Magick Development Team),please
# check the ChangeLog* files that come with this distribution.
#
# Third Party Changes (please include e-mail address):
#
# N/A
#
# =======================================================================
#
# Add a patch version
#

if [ -z "$*" ]; then
	echo "Must specify patch name"
	exit 1
fi

if [ ! -f include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd include
if [ -n "`grep PATCH version.h | grep \\\"$*\\\"`" ]; then
	echo "Patch has been previously applied.  Please remove first."
	exit 1
fi

rm -f version.h~
mv version.h version.h~
if [ -n "`grep PATCH1 version.h~ | grep '""'`" ]; then
	sed "s/PATCH1.*;/PATCH1			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH2 version.h~ | grep '""'`" ]; then
	sed "s/PATCH2.*;/PATCH2			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH3 version.h~ | grep '""'`" ]; then
	sed "s/PATCH3.*;/PATCH3			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH4 version.h~ | grep '""'`" ]; then
	sed "s/PATCH4.*;/PATCH4			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH5 version.h~ | grep '""'`" ]; then
	sed "s/PATCH5.*;/PATCH5			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH6 version.h~ | grep '""'`" ]; then
	sed "s/PATCH6.*;/PATCH6			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH7 version.h~ | grep '""'`" ]; then
	sed "s/PATCH7.*;/PATCH7			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH8 version.h~ | grep '""'`" ]; then
	sed "s/PATCH8.*;/PATCH8			= \"$*\";/" version.h~ >version.h
	exit 0
fi

if [ -n "`grep PATCH9 version.h~ | grep '""'`" ]; then
	sed "s/PATCH9.*;/PATCH9			= \"$*\";/" version.h~ >version.h
	exit 0
fi

echo "You've already patched Magick 9 times.  It might be"
echo "a good idea to revise and remove some of your patches!"
echo "DID NOT APPLY DUE TO TOO MANY PATCHLEVELS ..."
mv version.h~ version.h
exit 1
