#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2002 Preston Elder <prez@magick.tm>
# (c) 1998-2002 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the GNU General Public License, which
# means (in short), it may be distributed freely, and may not be sold
# or used as part of any closed-source product.  Please check the
# COPYING file for full rights and restrictions of this software.
#
# =======================================================================
#
# Gather and increment BUILD VERSION stuff
#

if [ -z "$1" ]; then
	echo "You must specify the TOPDIR for the Magick tree ..."
	exit 1
fi

if [ ! -f $1/include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd $1/include

build=`grep BUILD_NUMBER.*\=.*\; version.h | cut -f2 -d\= | cut -f1 -d\;`
build=`expr $build + 1`;

rm -f version.h~
mv version.h version.h~
sed	-e "s/BUILD_NUMBER.*;/BUILD_NUMBER = $build;/" \
	version.h~ >version.h
