#!/bin/sh
#
#  Magick IRC Services
#
# $Id$
# (c) 1997-2001 Preston Elder <prez@magick.tm>
# (c) 1998-2001 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any
# circumstances, however it may be added to if any
# modifications are made to this file.  All modified
# code must be clearly documented and labelled.
#
# ==========================================================
#
# Gather and increment BUILD VERSION stuff
#

if [ -z "$1" ]; then
	echo "You must specify the TOPDIR for the Magick tree ..."
	exit 1
fi

if [ ! -f $1/include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd $1/include

build=`grep BUILD_NUMBER.*\=.*\; version.h | cut -f2 -d\= | cut -f1 -d\;`
build=`expr $build + 1`;

rm -f version.h~
mv version.h version.h~
sed	-e "s/BUILD_NUMBER.*;/BUILD_NUMBER = $build;/" \
	-e "s/BUILD_TYPE.*;/BUILD_TYPE = \"`uname -mrsp 2>/dev/null`\";/" \
	-e "s/BUILD_SYS.*;/BUILD_SYS = \"`hostname`\";/" \
	version.h~ >version.h
