#!/bin/sh
#
# Gather and increment BUILD VERSION stuff

if [ -z "$1" ]; then
	echo "You must specify the TOPDIR for the Magick tree ..."
	exit 1
fi

if [ ! -f $1/include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd $1/include

# Change ident to ident_blah_h
#for x in `ls -1 *.h`; do
#    mv $x $x~
#    sed "s/\*ident.* =/\*ident_`echo $x | sed \"s/\./_/g\"` =/g" $x~ >$x
#    rm $x~
#done

build=`grep BUILD_NUMBER.*\=.*\; version.h | cut -f2 -d\= | cut -f1 -d\;`
build=`expr $build + 1`;

rm -f version.h~
mv version.h version.h~
sed	-e "s/BUILD_NUMBER.*;/BUILD_NUMBER = $build;/" \
	-e "s/BUILD_TYPE.*;/BUILD_TYPE = \"`uname -mrsp`\";/" \
	-e "s/BUILD_SYS.*;/BUILD_SYS = \"`hostname`\";/" \
	version.h~ >version.h
