#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2002 Preston Elder <prez@magick.tm>
# (c) 1998-2002 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the Artistic License v2.0 or better.
# The full text of this license should be contained in a file called
# COPYING distributed with this code.  If this file does not exist,
# it may be viewed here: http://www.magick.tm/m2/license.html
#
# =======================================================================
#
# For official changes (by the Magick Development Team),please
# check the ChangeLog* files that come with this distribution.
#
# Third Party Changes (please include e-mail address):
#
# N/A
#
# =======================================================================
#
# Re-create language.h
#

if [ -z "$1" ]; then
	echo "You must specify a language file to convert."
	echo "Syntax: $0 langfile"
	exit 1
elif [ ! -f lang/$1 -a ! -f lang/$1.lng ]; then
	echo "Language file $1 does not exist."
	exit 1
fi


if [ -f include/language.h ]; then
	if [ -f lang/$1 ]; then
		LANG=lang/$1
	else
		LANG=lang/$1.lng
	fi
	DATE=`date`

	cat >include/language.h <<EOF
#ifndef WIN32
#pragma interface
#endif
/* Magick IRC Services
**
** (c) 1997-2002 Preston Elder <prez@magick.tm>
** (c) 1998-2002 William King <ungod@magick.tm>
**
** The above copywright may not be removed under any circumstances,
** however it may be added to if any modifications are made to this
** file.  All modified code must be clearly documented and labelled.
**
** This code is released under the Artistic License v2.0 or better.
** The full text of this license should be contained in a file called
** COPYING distributed with this code.  If this file does not exist,
** it may be viewed here: http://www.magick.tm/m2/license.html
**
** ======================================================================= */
#ifndef _LANGUAGE_H
#define _LANGUAGE_H
#include "pch.h"
RCSID(language_h, "@(#) \$Id\$");

/* ======================================================================= **
**
** For official changes (by the Magick Development Team),please
** check the ChangeLog* files that come with this distribution.
**
** Third Party Changes (please include e-mail address):
**
** N/A
**
** ======================================================================= */


/*
** Automatically generated hard-coded language file.
** Based upon $LANG.
** Created on $DATE
*/

EOF
	echo "const unsigned int def_langent = `cat $LANG | wc -l`;" >>include/language.h
	echo "const char *def_lang[] = {" >>include/language.h
	sed -e "s/\\\\/\\\\\\\\/g" -e "s/\"/\\\\\"/g" -e "s/^/\"/g" \
		-e "s/$/\",/g" $LANG >>include/language.h
	echo "\"\" };" >>include/language.h
	echo "#endif" >>include/language.h
	
	echo "include/language.h created successfully."
else
	echo "Existing language.h file missing."
	echo "To create one, type: > include/language.h"
	echo "Then re-run this script."
fi
