#!/bin/sh
#
# Remove a patch version

if [ -z "$*" ]; then
	echo "Must specify patch name"
	exit 1
fi

if [ ! -f include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd include
if [ -z "`grep PATCH version.h | grep \\\"$*\\\"`" ]; then
	echo "Patch has not been applied."
	exit 1
fi

patchlevel=`grep PATCH version.h | grep \"$*\" | awk '{print $3}'`
rm -f version.h~
mv version.h version.h~
sed "s/$patchlevel.*;/$patchlevel			= \"\";/" version.h~ >version.h
exit 0
