#!/bin/sh
#
#  Magick IRC Services
#
# $Id$
# (c) 1997-2001 Preston Elder <prez@magick.tm>
# (c) 1998-2001 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any
# circumstances, however it may be added to if any
# modifications are made to this file.  All modified
# code must be clearly documented and labelled.
#
# ==========================================================
#
# Remove a patch version
#

if [ -z "$*" ]; then
	echo "Must specify patch name"
	exit 1
fi

if [ ! -f include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd include
if [ -z "`grep PATCH version.h | grep \\\"$*\\\"`" ]; then
	echo "Patch has not been applied."
	exit 1
fi

patchlevel=`grep PATCH version.h | grep \"$*\" | awk '{print $3}'`
rm -f version.h~
mv version.h version.h~
sed "s/$patchlevel.*;/$patchlevel			= \"\";/" version.h~ >version.h
exit 0
