#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2002 Preston Elder <prez@magick.tm>
# (c) 1998-2002 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the GNU General Public License, which
# means (in short), it may be distributed freely, and may not be sold
# or used as part of any closed-source product.  Please check the
# COPYING file for full rights and restrictions of this software.
#
# =======================================================================
#
# Remove a patch version
#

if [ -z "$*" ]; then
	echo "Must specify patch name"
	exit 1
fi

if [ ! -f include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd include
if [ -z "`grep PATCH version.h | grep \\\"$*\\\"`" ]; then
	echo "Patch has not been applied."
	exit 1
fi

patchlevel=`grep PATCH version.h | grep \"$*\" | awk '{print $3}'`
rm -f version.h~
mv version.h version.h~
sed "s/$patchlevel.*;/$patchlevel			= \"\";/" version.h~ >version.h
exit 0
