#!/bin/sh
#
# Gather and increment BUILD VERSION stuff

if [ -z "$1" ]; then
	echo "You must specify the TOPDIR for the Magick tree ..."
	exit 1
fi

if [ ! -f $1/include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd $1/include

mv version.h version.h~
sed	-e "s/BUILD_NUMBER.*;/BUILD_NUMBER = 0;/" \
	-e "s/BUILD_TYPE.*;/BUILD_TYPE = \"32-Bit Windows\";/" \
	-e "s/BUILD_SYS.*;/BUILD_SYS = \"localhost\";/" \
	version.h~ >version.h
