#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2003 Preston Elder <prez@magick.tm>
# (c) 1998-2003 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the Artistic License v2.0 or better.
# The full text of this license should be contained in a file called
# COPYING distributed with this code.  If this file does not exist,
# it may be viewed here: http://www.magick.tm/m2/license.html
#
# =======================================================================
#
# For official changes (by the Magick Development Team),please
# check the ChangeLog* files that come with this distribution.
#
# Third Party Changes (please include e-mail address):
#
# N/A
#
# =======================================================================
#
# Reset version stuff to original form
#

if [ -z "$1" ]; then
	echo "You must specify the TOPDIR for the Magick tree ..."
	exit 1
fi

if [ ! -f $1/include/version.h ]; then
	echo "This must be run from the MAIN COMPILE directory"
	exit 1
fi

cd $1/include

mv version.h version.h~
sed	-e "s/BUILD_NUMBER.*;/BUILD_NUMBER = 0;/" \
	version.h~ >version.h
