#!/bin/sh
#
# Magick IRC Services
#
# $Id$
# (c) 1997-2002 Preston Elder <prez@magick.tm>
# (c) 1998-2002 William King <ungod@magick.tm>
#
# The above copywright may not be removed under any circumstances,
# however it may be added to if any modifications are made to this
# file.  All modified code must be clearly documented and labelled.
#
# This code is released under the Artistic License v2.0 or better.
# The full text of this license should be contained in a file called
# COPYING distributed with this code.  If this file does not exist,
# it may be viewed here: http://www.magick.tm/m2/license.html
#
# =======================================================================
#
# For official changes (by the Magick Development Team),please
# check the ChangeLog* files that come with this distribution.
#
# Third Party Changes (please include e-mail address):
#
# N/A
#
# =======================================================================
#
# This is a script suitable for use in a crontab.  It checks to make sure
# your services are running.  If your services arn't found, it'll try to
# start them back up.  This script is based on the Eggdrop crontab script.
#
# You'll need to edit this script for your services.
#
# To check for your services every 10 minutes, put the following line in your
# crontab:
#    0,10,20,30,40,50 * * * *   /home/mydir/serviceschk
# And if you don't want to get email from crontab when it checks your
# services, put the following in your crontab:
#    0,10,20,30,40,50 * * * *   /home/mydir/serviceschk >/dev/null 2>&1
#

# Terminate Check (uncomment to terminate the auto-start).
exit 0

# change this to the directory you run your services from.
servicesdir="/usr/local/lib/services"

# IF ace isnt in your LD_LIBRARY_PATH, location of ACE library
# (you will see an error like 'Cannot find libACE.so' if you
# need this -- this should be the path where libACE.so is).
acelibdir="/usr/local/lib"

# command to start services if they're not running.
startcommand="./magick"

# change this to whatever your PID file is called.
pidfile="magick.pid"

# change this to whatever your database file is called.
dbfile="magick.mnd"

# How old should the dbfile be before we consider the
# 'running' process to be dead (ie. no save has happened!).
# Setting this to '0' stops the save time check.
savetime=0

# Set this to either 0 to suppress a core file, unlimited to
# allow a core file of any size, or the maximum core file size.
coresize=unlimited

# Name of the coredump file magick will dump, on freebsd, this is
# the name of the process executed with a '.core' extension, on all
# other platforms, its just 'core'
corename="core"

# Maximum number of coredump files to keep
maxcores=7

########## you probably don't need to change anything below here ##########

cd $servicesdir
if test -r ${pidfile}; then
  # there is a pid file -- is it current?
  servicespid=`cat ${pidfile}`
  if `kill -0 $servicespid >/dev/null 2>&1`; then
    if test 0$savetime -gt 0; then
      # it's still going
      if test -n "`find . -name $dbfile -mmin +$savetime 2>/dev/null`"; then
        echo "Killing non-responding services ..."
        kill -9 $servicespid
      else
        # backout quietly
        exit 0
      fi
    else
      # it's still going
      # back out quietly
      exit 0
    fi
  fi
  echo ""
  echo "Stale ${pidfile} file (erasing it)"
  rm -f ${pidfile}
fi
echo ""
echo "Couldn't find the services running.  Starting them ..."
echo ""

# If a new file exists, we died while saving ...
if test -s $dbfile.new; then
  # If an old file exists, the new was finished
  if test -s $dbfile.old; then
    cp $dbfile.old $dbfile
  fi
  rm -f $dbfile.old $dbfile.new
elif test -s $dbfile.old; then
  rm -f $dbfile.old
fi

# Keep old cores ...
if test 0$maxcores -gt 0; then
  if test -f $corename; then
    i=`expr 0$maxcores - 1`
    while test 0$i -gt 0; do
      if test -f $corename.$i; then
        mv $corename.$i $corename.`expr 0$i + 1`
      fi
      i=`expr 0$i - 1`
    done
    mv $corename $corename.1
  fi
fi

# Finally, start up services ...
ulimit -c $coresize 2>/dev/null
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$acelibdir"
export LD_LIBRARY_PATH
touch $dbfile
$startcommand

exit 0
