=head1 NAME

magick - IRC Services

=head1 SYNOPSIS

magick [B<OPTIONS>]

=head1 DESCRIPTION

Magick IRC Services are a program that is designed to interface
with an Internet Relay Chat (IRC) network, and offer its users,
operators and administrators services such as the ability to
register nicknames so they cannot be taken by anyone else, the
ability to register channels with pre-defined access lists and
kick lists so that channels may not be taken over, the ability
to leave offline messages for other users, and many network
control mechanisms to stop things like flooding, abusive users,
and many other things.

Magick services adhere to B<RFC 1459>, and many variants of it.
The changes to the base protocol will not be discussed in this
document, as there are too many of them, and so many different
distinct protocols around nowadays, however Magick has been
designed to cope with them all, with a minimum of fuss (as long
as they support services of this nature).

=head1 OPTIONS

=over 4

=item --help, -?

Help output (summary of the below).

=item --dir X

Set the initial services directory - this is the default location
to look for the F<magick.ini> file, and the point of reference
for any files specified within it that do not have absolute paths.

=item --config X

Set the name of the config file, if not specified, F<magick.ini>
will be used, and looked for in the services directory.

=item --nofork

This will stop Magick from becoming a background process (ie. leave
it in the foreground).  This option is not available on Windows
versions of Magick.

=item --convert X

THIS OPTION WILL ONLY APPEAR IF COMPILED INTO THE BINARY!

Convert another version of services databases to Magick II format,
where X is the type of database to convert.  Currently recognised:

=over 4

=item *

magick (1.4)

=item *

esper (4.4.8)

=item *

epone (1.4.7)

=item *

sirv (N/A)

=back

=item --trace X:Y

THIS OPTION WILL ONLY APPEAR IF COMPILED INTO THE BINARY!

Set the trace level on startup, equivalent of using the OperServ
TRACE SET command while running, where X is the trace type (or ALL),
and Y is the trace level in hex.

=item --name X, -n

Override the B<STARTUP/SERVER_NAME> value in the configuration file,
which is the name Magick will use to connect to an IRC network with.

=item --desc X, -d

Override the B<STARTUP/SERVER_DESC> value in the configuration file,
which is the server description (free text) services will display.

=item --user X, -u

Override the B<STARTUP/SERVICES_USER> value in the configuration file,
which is the user part of services user@host for its clients.

=item --host X, -h

Override the B<STARTUP/SERVICES_HOST> value in the configuration file,
which is the host part of services user@host for its clients.

=item --ownuser, -o

Override the B<STARTUP/OWNUSER> value in the configuration file,
which makes each service connect with their own nickname in lower
case as the user in their user@host (making B<STARTUP/SERVICES_USER>
useless).

=item --protocol X, -P

Override the B<STARTUP/PROTOCOL> value in the configuration file,
which tells magick how to talk to the IRC server it links to.

=item --level X, -l

Override the B<STARTUP/LEVEL> value in the configuration file,
which is the lowest services level Magick may have while active
(for services fail over purposes, higher level = less likely to
be failed to).

=item --lagtime X, -g

Override the B<STARTUP/LAGTIME> value in the configuration file,
which is the average server lag threshold to cause us to raise
or lower our live level (but never less than B<STARTUP/LEVEL>).

=item --verbose, -v

Override the B<FILES/VERBOSE> value in the configuration file,
setting it to true, which enables the 'DEBUG' log level, essentially
logging all successful commands to services.

=item --log X, -L

Override the B<FILES/LOG> value in the configuration file,
which is the file to output all log output to, this defaults to
F<magick.log>.

=item --logchan X, -C

Override the B<FILES/LOGCHAN> value in the configuration file,
which is the channel to output all log output to, this defaults
to nothing (ie. no channel output).

=item --dbase X, -D

Override the B<FILES/DBASE> value in the configuration file,
which is Magick New Database file, this defaults to F<magick.mnd>.

=item --langdir X, -S

Override the B<FILES/LANGDIR> value in the configuration file,
which is where magick will look for all F<*.lng>, F<*.lfo> and
F<*.hlp> files for language translation to IRC clients, this
defaults to lang and is a I<DIRECTORY>, not a filename.

=item --encrypt, -E

Override the B<FILES/ENCRYPTION> value in the configuration file,
setting it to true, which tells magick to encrypt the databases
next time it saves (depends on the F<magick.key> file existing).

I<NOTE>: if your F<magick.key> file was created with a
F<magick_keygen> binary stamped with different keyfile keys than
the ones the current version of F<magick> you are running was
stamped with, you will essentially create corrupted databases.

=item --decrypt, -e

Override the B<FILES/ENCRYPTION> value in the configuration file,
setting it to false, which tells magick to decrypt the databases
on load, and not re-encrypt it when it saves them.  This requires
your F<magick.key> file to have the correct keys to decrypt the
databases (and to have been created with a version of
F<magick_keygen> that is stamped with the same keyfile keys as 
the current version of your F<magick> binary).

=item --keyfile X, -K

Override the B<FILES/KEYFILE> value in the configuration file,
which is the file that contains the keys to decrypt or encrypt
databases.  This file is created with the F<magick_keygen> program.
You MUST ensure you are using a version of F<magick_keygen> and
F<magick> that were stamped with the same keyfile keys.  This
defaults to F<magick.key>.

=item --compress X, -c

Override the B<FILES/COMPRESSION> value in the configuration file,
which tells magick how much (if at all) to compress the magick
databases.  The values for this may be between 0 and 9.

=item --relink X, -r

Override the B<CONFIG/SERVER_RELINK> value in the configuration file,
which tells magick how long to wait before trying to connect back
to a server when it has been disconnected.

=item --cycle X, -t

Override the B<CONFIG/CYCLETIME> value in the configuration file,
which is the delay between things like checking for expirations.

=item --save X, -w

Override the B<CONFIG/SAVETIME> value in the configuration file,
which is the delay between saving the database file.

=item --check X, -T

Override the B<CONFIG/CHECKTIME> value in the configuration file,
which is the delay between things like checking for outbound
channel modes, who we need to rename because they haven't ident'd,
if we need to unban any bans, and other checks that happen quickly.

=item --ping X, -p

Override the B<CONFIG/CHECKTIME> value in the configuration file,
which is the delay between pinging all servers to find the average
lag on the network (to determine if we should increase or decrease
our live level).

=item --threads X, -X

Override the B<CONFIG/MIN_THREADS> value in the configuration file,
which is the minimum number of 'worker' threads to keep active.
This defaults to 2, mainly so we could have one doing something
difficult and time consuming like loading a language file, and
the other can still keep handling requests.  This number is a
minimum, so the number of threads can and will increase.

=item --lwm X, -m

Override the B<CONFIG/LOW_WATER_MARK> value in the configuration file,
which is a number to help in the releasing of old
threads to reduce overhead, basically the equation is

C<if (((No_of_Threads - 2) * High_Water_Mark) + Low_Water_Mark E<gt>
No_Unprocessed_Messages && No_of_Threads E<gt> 1)>

then release a thread from the pool.

=item --hwm X, -M

Override the B<CONFIG/HIGH_WATER_MARK> value in the configuration file,
which is a number to help in the spawning of new
threads to handle load, basically the equation is

C<if (No_of_Threads * High_Water_Mark E<lt> No_Unprocessed_Messages)>

then spawn a new thread off and add it to the pool.

=item --append, -a

Override the B<CONFIG/APPEND_RENAME> value in the configuration file,
setting it to true, which tells magick to, when renaming a user,
try to append one, then two, then three, etc until the maximum
nickname length of each character (in order) of the CONFIG/SUFFIXES
option.

Example: PreZ becomes PreZ_ then PreZ__ and so on, and if it cannot
find a successful match, it tries PreZ- then PreZ-- and so on.

=item --rename, -A

Override the B<CONFIG/APPEND_RENAME> value in the configuration file,
setting it to false, which tells magick to, when renaming a user,
take the value of B<CONFIG/SUFFIXES>, add a random 5 digit number to
it, and name the user that.

Example: PreZ becomes Guest73923

=item --ident X, -R

Override the B<NICKSERV/IDENT> value in the configuration file,
which is the amount of time to wait for an identify from a user
that is secure.

=item --language X, -s

Override the B<NICKSERV/DEF_LANGUAGE> value in the configuration file,
which is the language services will speak by default, and the language
services will output its log files in.  Users will have this as their
language by default when they register their nicknames.

=item --nodcc, -x

Override the B<NICKSERV/PICEXT> value setting it to a blank string
and the B<MEMOSERV/FILES> value setting it to 0.
This essentially disables ALL DCC transfers in magick except
the Public FileSystem (which only SOP's can upload to, and they
may specify who may download each file they upload).

=item --inflight X, -f

Override the B<MEMOSERV/INFLIGHT> value in the configuration file,
which is the amount of time to wait before actually sending a
memo to another use (giving the user time to cancel it, extend
it, or start a DCC transfer if they are attaching a file).

=item --logignore, -i

Override the B<OPERSERV/LOG_IGNORE> value in the configuration file,
which tells magick to log all messages received by a user that is
ignored by services.  These messages are logged with a priority
of DEBUG, so you will need B<FILES/VERBOSE> set to true to see them.

=item --ignore X, -I

Override the B<OPERSERV/IGNORE_METHOD> value in the configuration file,
which is the default method magick will use to ignore users when
an automatic ignore is set.  The available options are:

=over 4

=item 1

nick!*@*

=item 2

nick!user@port.host

=item 3

nick!user@*.host

=item 4

nick!*@port.host

=item 5

nick!*@*.host

=item 6

*!user@port.host

=item 7

*!user@*.host

=item 8

*!*@port.host

=item 9

*!*@*.host

=back

=back

=head1 FILES

F<magick.ini> Magick Configuration File

F<magick.log> General log output file

F<magick.mnd> Magick New Database (mnd) file

F<magick.key> Key file for database encryption

F<magick.motd> Reply to Message of the Day requests

F<magick.pid> File containing PID of running version

F<*.lng> Response files, which contain the responses to ALL commands
executed by IRC clients.

F<*.lfo> Log File Output files, which contain the text that will be
logged to the magick log file.

F<*.hlp> Help files, which contain ALL the text that is sent back as
a reply to any HELP request.

=head1 SEE ALSO

L<magick_keygen(1)>, L<magick_stampkeys(1)>

=head1 NOTES

Magick may be obtained from B<http://www.magick.tm> or
B<ftp://ftp.magick.tm/pub/magick.tm> and is distributed under
the I<GNU General Public License>.

=head1 DEDICATION

Magick is dedicated to the memory of PreZ's loving sister,
Stacey Louise Elder (1st Jan, 1975 - 25th Feb, 1998). She
has been there for me more than anyone over the years, and I
was distraught when she died, may her Lord love her as much
as I did, and keep her safe like I could not. Merry Parting,
Dear Sister.

Magick is also dedicated to the memory of Ungod's brother,
Edward Kevin King (28th Aug, 1982 - 21st Nov, 1997), His
life was short, but his memory is great, never will those
who knew him forget him.

=head1 AUTHORS

Magick Development Team E<lt>magick-devel@magick.tmE<gt>

(c) 1997-2001 Preston Elder E<lt>prez@magick.tmE<gt>

(c) 1998-2001 William King E<lt>ungod@magick.tmE<gt>
