=head1 NAME

magick_keygen - Key file generator for Magick IRC Services

=head1 SYNOPSIS

magick_keygen [B<keyfile>]

=head1 DESCRIPTION

This will generate an encrypted keyfile using two hard-coded keys
in the binary (that are shared with the Magick binary) to ensure
that the actual keys used for Magick databases is never readable.

If no parameters are specified, the program will first ask you for
the output key filename (defaulting to F<magick.key>), and then it
will ask you to enter the unencrypted keys twice.

This program is written for use with Magick IRC Services, and contains
the two keys it will use to generate the keyfile stamped into it.
This means if your copy of F<magick> and F<magick_keygen> were not stamped
with the same keys, the keys this program will generate will be invalid.

=head1 OPTIONS

=over 4

=item keyfile

This is the output file that the keyfile will be generated to.  This
defaults to magick.key.

=back

=head1 

=head1 FILES

Specified in program.

=head1 SEE ALSO

L<magick(1)>, L<magick_stampkeys(1)>

=head1 BUGS

The keys you type in may show up on the screen.  It is not supposed
to. This is due to the fact your system does not have TERMIO, which
is required to 'hide' the keystrokes.  Hopefully later other
methods of hiding keystrokes will be implemented.

=head1 NOTES

Magick may be obtained from B<http://www.magick.tm> or
B<ftp://ftp.magick.tm/pub/magick.tm> and is distributed under
the I<GNU General Public License>.

You will need to re-generate your Magick database keys (with the
same keys entered the first time) each time you re-stemp the
F<magick> and F<magick_keygen> binaries.

If you forget the plain text key needed to re-generate your keyfile,
or wish to change the plain text key, you must:

=over 4

=item *

Set the B<Files/ENCRYPTION> option to FALSE, then load up magick
(leaving the existing keyfile in the current directory).  Magick
will detect the databases are encrypted, and decrypt them anyway.

=item *

Trigger a database UPDATE to save your databases unencrypted, and
remove the existing keyfile.

=item *

If you are upgrading your version of magick (ie. your new binaries
are stamped with different keyfile keys than the current ones),
then shut down magick, and copy in your new magick and magick_keygen
binaries.

=item *

Generate a new keyfile with the magick_keygen program, and set the
B<Files/ENCRYPTION> option back to TRUE.

=item *

Start up magick again if you shut it down before, or trigger a
config RELOAD from within magick.  Next save, your databases will
be encrypted with the new key.

=back

=head1 DEDICATION

Magick is dedicated to the memory of PreZ's loving sister,
Stacey Louise Elder (1st Jan, 1975 - 25th Feb, 1998). She
has been there for me more than anyone over the years, and I
was distraught when she died, may her Lord love her as much
as I did, and keep her safe like I could not. Merry Parting,
Dear Sister.

Magick is also dedicated to the memory of Ungod's brother,
Edward Kevin King (28th Aug, 1982 - 21st Nov, 1997), His
life was short, but his memory is great, never will those
who knew him forget him.

=head1 AUTHORS

Magick Development Team E<lt>magick-devel@magick.tmE<gt>

(c) 1997-2001 Preston Elder E<lt>prez@magick.tmE<gt>

(c) 1998-2001 William King E<lt>ungod@magick.tmE<gt>
